// <auto-generated />
using System;
using LSS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LSS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240112080608_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LSS.Model.LoanDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("boarding_date")
                        .HasColumnType("date");

                    b.Property<float>("current_rate")
                        .HasColumnType("real");

                    b.Property<long>("loan_number")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateOnly>("note_date")
                        .HasColumnType("date");

                    b.Property<float>("note_rate")
                        .HasColumnType("real");

                    b.Property<float>("pmt_amount")
                        .HasColumnType("real");

                    b.Property<DateOnly>("pmt_due_date")
                        .HasColumnType("date");

                    b.Property<string>("ppr")
                        .HasColumnType("text");

                    b.Property<float>("principal_intrest")
                        .HasColumnType("real");

                    b.Property<float>("tax_insurance")
                        .HasColumnType("real");

                    b.Property<float>("upb_amount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("loan_number")
                        .IsUnique();

                    b.ToTable("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
